version: "3.7"

services:
  daemon:
    image: iptestground/testground:edge
    ports:
      - 8042
    volumes:
      - ${COMPOSE_HOST_PATH:-.}/.env.toml:/root/testground/.env.toml

  client:
    image: iptestground/testground:edge
    volumes:
      - ${COMPOSE_HOST_PATH:-.}/:/root/testground/
    entrypoint: testground
    command: |
      --endpoint http://daemon:8042
      run single
      --plan=ipfssync
      --testcase=accept
      --builder=docker:go
      --runner=local:docker
      --instances=5
      --wait
    links:
      - daemon
