---
name: Docker Releases

on:
  push:
    branches:
      - dev
      - stage
      - master
      - main
  pull_request:

jobs:
  job_docker_release:
    runs-on: ubuntu-latest
    needs: [job_go_test, job_compose_test]
    if: |
      github.ref == 'refs/heads/master'
      || github.ref == 'refs/heads/stage'
      || startsWith(github.ref, 'refs/heads/release')
      || github.ref == 'refs/heads/dev'
      || github.ref == 'refs/heads/apiv2'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get branch name, git commit hash and current time in secs
        id: vars
        shell: bash
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )" >> $GITHUB_OUTPUT
          echo "GIT_HASH_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "DATE_IN_SECS=$(date +%s)" >> $GITHUB_OUTPUT

  job_go_build_for_mac:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run go build for Mac
        run: |
          # Some of our devs are on Mac. Ensure it builds.
          # It's surprisingly hard with some deps like bazil.org/fuse.
          GOOS=darwin go build ./...

