---
name: Testground ipfsSync

on:
  push:
    paths:
      - 'cmd/ipfsSync/**'
      - 'ipfssync/**'
  pull_request:
    paths:
      - 'cmd/ipfsSync/**'
      - 'ipfssync/**'

jobs:
  testground-ipfssync:
    runs-on: [self-hosted, testground]
    #if: github.repository == 'vocdoni/vocdoni-node'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run testground
        run: |
          export TESTGROUND_HOME=./testground/
          testground run single --plan=ipfssync --testcase=accept --builder=docker:go --runner=local:docker --instances=5
